---
# tasks file for packages
- name: Run "apt-get update"
  ansible.builtin.apt:
    update_cache: yes

- name: Install system dependencies
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-dev
      - python3-pip
      - software-properties-common
      - ca-certificates
      - apt-transport-https
      # apt-transport-tor
      # - ufw
      
- name: Remove unnecessary packages and run "apt-get clean"
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes